runtime: python38
env: standard
instance_class: F4_HIGHMEM

entrypoint: gunicorn -b :$PORT main:app


handlers:
- url: /
  script: auto

- url: /static
  static_dir: static
 
  http_headers:   
    Access-Control-Allow-Origin: https://imageproj1.uc.r.appspot.com
    Access-Control-Allow-Origin: https://imagexp.ploessl.org
    Access-Control-Allow-Origin: http://imagexp.ploessl.org